# Generated by Django 3.0.5 on 2020-04-08 11:21

from faker import Faker
from django.db import migrations


def populate_with_initial_data(apps, schema_editor, number_of_data=100):
    objs = []
    faker = Faker()
    # We can't import the Speaker model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    speaker_model = apps.get_model('speaker', 'Speaker')

    for _ in range(number_of_data):
        objs.append(
            speaker_model(
                first_name=faker.name(),
                last_name=faker.name(),
                email=faker.email(),
            )
        )

    # Inserts the provided list of objects into the database in an efficient manner
    speaker_model.objects.bulk_create(objs)


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_with_initial_data)
    ]
