# Generated by Django 3.0.5 on 2020-04-08 13:30
import uuid
import random

from django.db import (
    models,
    migrations
)


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0002_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='Speaker',
            name='full_name',
            field=models.CharField(
                max_length=254,
                default=uuid.uuid4,
                blank=True),
        ),
    ]
