# Generated by Django 3.0.5 on 2020-04-08 13:31

from django.db import migrations


def populate_full_name_values(apps, schema_editor):
    speaker_model = apps.get_model('speaker', 'Speaker')

    for speaker in speaker_model.objects.all():
        speaker.full_name = f'{speaker.first_name} {speaker.last_name}'
        speaker.save(update_fields=['full_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0003_add_full_name_field'),
    ]

    operations = [
        migrations.RunPython(populate_full_name_values)
    ]
