# Generated by Django 3.0.5 on 2020-04-09 10:37

from django.db import (
    models,
    migrations
)


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0004_populate_full_name_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Speaker',
            name='full_name',
            field=models.CharField(
                max_length=254,
                unique=True
            )
        )
    ]
