# Generated by Django 3.0.5 on 2020-04-10 11:57

from django.db import migrations


def create_temporary_speaker(apps, schema_editor):
    # We can't import the Speaker model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    speaker_model = apps.get_model('speaker', 'Speaker')
    speaker_model.objects.create(
        full_name='Private',
        email='no_reply@speaker.com'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0005_remove_full_name_null_constraint'),
    ]

    operations = [
        migrations.RunPython(create_temporary_speaker)
    ]
