# Generated by Django 3.0.5 on 2020-04-10 10:21

from faker import Faker
from django.db import migrations


def populate_with_initial_data(apps, schema_editor, number_of_data=100):
    objs = []
    faker = Faker()
    # We can't import the Event model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    event_model = apps.get_model('event', 'Event')

    for _ in range(number_of_data):
        objs.append(
            event_model(title=faker.sentence())
        )

     # Inserts the provided list of objects into the database in an efficient manner
    event_model.objects.bulk_create(objs)


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_with_initial_data)
    ]
