# Generated by Django 3.0.5 on 2020-04-10 11:49

from django.db import migrations


def get_private_speaker_id(apps, schema_editor):
    # We can't import the Event model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    speaker_model = apps.get_model('spaker', 'Speaker')


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='Event',
            name='speaker',
            field=models.ForeignKey(
                default=1,
                to='speaker.Speaker',
                related_name='events',
                on_delete=django.db.models.deletion.CASCADE,
            ),
            preserve_default=False,
        )
    ]
